### ISSUE TITLE
__main__.py: error: the following arguments are required: --model

### ISSUE THREAD

**Issue by toddpage** [slackr31337/wyoming-whisper-gpu#5]
Getting the following error when trying to runt wyoming-whistper

```
whisper exited with code 2
whisper       | usage: __main__.py [-h] --model
whisper       |                    {tiny,tiny-int8,base,base-int8,small,small-int8,medium,medium-int8}
whisper       |                    --uri URI --data-dir DATA_DIR [--download-dir DOWNLOAD_DIR]
whisper       |                    [--device DEVICE] [--language LANGUAGE]
whisper       |                    [--compute-type COMPUTE_TYPE] [--beam-size BEAM_SIZE]
whisper       |                    [--debug]
whisper       | __main__.py: error: the following arguments are required: --model
whisper exited with code 2
```

**Comment by slackr31337** [comment]
For this docker image you have to pass an argument to define which model you want to use. I was thinking of using an environment variable to set the model.

Example:
    --model tiny-int8

Compose: 

  whisper:  
    image: slackr31337/wyoming-whisper-gpu:latest
    container_name:whisper
    command: --model tiny-int8
    ports:  
      - 10300:10300

**Comment by toddpage** [comment]
Think I got it working now!  the python3 seems to be whisper. trying to figure out how to change that to another name.


```

Tue Jan 14 00:03:10 2025
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA RTX A2000 12GB          On  | 00000000:01:00.0 Off |                  Off |
| 30%   54C    P2              23W /  70W |    955MiB / 12282MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      5732      G   /usr/lib/xorg/Xorg                           46MiB |
|    0   N/A  N/A      5854      G   /usr/bin/gnome-shell                         42MiB |
|    0   N/A  N/A   1956691      C   python3                                     442MiB |      <=  Whisper
|    0   N/A  N/A   1956699      C   /app/piper/piper                            392MiB |
+---------------------------------------------------------------------------------------+

```



Another GPU Monitor

```
Device 0 [NVIDIA RTX A2000 12GB] PCIe GEN 3@16x RX: 0.000 KiB/s TX: 0.977 MiB/s
 GPU 780MHz  MEM 5000MHz TEMP  53°C FAN  30% POW  23 /  70 W
 GPU[                                0%] MEM[||||              1.375Gi/11.994Gi]
   ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
100│                                                                                                       GPU 0│
   │                                                                                                         MEM│
   │                                                                                                            │
   │                                                                                                            │
   │                                                                                                            │
75%│                                                                                                            │
   │                                                                                                            │
   │                                                                                                            │
   │                                                                                                            │
   │                                                                                                            │
50%│                                                                                                            │
   │                                                                                                            │
   │                                                                                                            │
   │                                                                                                            │
   │                                                                                                            │
25%│                                                                                                            │
   │                                                                                                            │
   │────────────────────────────────────────────────────────────────────────────────────────────────────────────│
   │                                                                                                            │
 0%│────────────────────────────────────────────────────────────────────────────────────────────────────────────│
   └────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
    PID       USER GPU    TYPE        GPU MEM    CPU  HOST MEM Command                                             
1956691       root   0 Compute    442MiB   4%     0%   1485MiB python3 -m wyoming_faster_whisper --uri tcp://0.0.0.
1956699       root   0 Compute    392MiB   3%     0%    526MiB /app/piper/piper --model /data/en_US-amy-medium.onnx
   5732       root   0 Graphic     46MiB   0%     0%     66MiB /usr/lib/xorg/Xorg vt2 -displayfd 3 -auth /run/user/
   5854       todd   0 Graphic     42MiB   0%     0%    294MiB /usr/bin/gnome-shell

```


Here is my docker-compose:

```
  whisper:  
    #image: homeassistant/amd64-addon-whisper:latest  
    image: slackr31337/wyoming-whisper-gpu:latest  
    container_name: whisper  
  
    # tiny, tiny-int8, base, base-int8, small, small-int8, medium, medium-int8  
    command: >  
      --language en 
      --device cuda
      --model base-int8 
     
    ports:  
      - 10300:10300  
    environment:  
      - TZ=America/Chicago  
    volumes:  
      - /opt/voiceAssistant/whisper-data:/data  
      - /usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.7:/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8:ro
      - /usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.7:/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8:ro
      - /usr/lib/x86_64-linux-gnu/libcublasLt.so.11:/usr/lib/x86_64-linux-gnu/libcublasLt.so.12:ro
      - /usr/lib/x86_64-linux-gnu/libcublas.so.11:/usr/lib/x86_64-linux-gnu/libcublas.so.12:ro
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - utility
                - compute

```

**Comment by toddpage** [comment]
Notice you you pushed an update this morning. Just updated and now I get the following error.

```
whisper       | INFO:__main__:Ready
whisper       | INFO:faster_whisper:Processing audio with duration 00:03.320
whisper       | Unable to load any of {libcudnn_ops.so.9.1.0, libcudnn_ops.so.9.1, libcudnn_ops.so.9, libcudnn_ops.so}
whisper       | Invalid handle. Cannot load symbol cudnnCreateTensorDescriptor
whisper       | /app/run.sh: line 10:     6 Aborted                 (core dumped) /app/bin/python3 -m wyoming_faster_whisper --uri 'tcp://0.0.0.0:10300' --data-dir /data --download-dir /data --model "${MODEL:-tiny-int8}" --language "${LANGUAGE:-en}" --device cuda "$@"
whisper exited with code 0
whisper       | INFO:__main__:Ready
```

**Comment by slackr31337** [comment]
Try removing these volumes from your docker compose. That image has updated libraries.

      - /usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.7:/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8:ro
      - /usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.7:/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8:ro
      - /usr/lib/x86_64-linux-gnu/libcublasLt.so.11:/usr/lib/x86_64-linux-gnu/libcublasLt.so.12:ro
      - /usr/lib/x86_64-linux-gnu/libcublas.so.11:/usr/lib/x86_64-linux-gnu/libcublas.so.12:ro

**Comment by toddpage** [comment]
Have not had a chance to give it a try yet.  Been offline due to sickness

**Comment by toddpage** [comment]
Seems to be working.

Here is my docker-compose:

```
  whisper: 
    image: slackr31337/wyoming-whisper-gpu:latest  
    container_name: whisper  
    environment:  
      - MODEL=base-int8
      - LANGUAGE=en
      - COMPUTE_TYPE=int8
      - BEAM_SIZE=5
      - DEVICE=cuda
    ports:  
      - 10300:10300
    volumes:  
      - /path/to/persistent/data:/data   
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - utility
                - compute
```
